### ISSUE TITLE
is this work for mobile devices?

### ISSUE THREAD

**Issue by danieltigse** [gbentaieb/simple360Player#1]
I mean android and iOS

**Comment by gbentaieb** [comment]
Hi!

Sorry, my answer comes a bit late! :)
No this does not: this project is just a demo on how to use three.js to build a simple 360 web player.
But if you want you can checkout out my other repository https://github.com/gbentaieb/simple-360-player
This is an npm package that provides tools to integrate 360 players in your project. And it works on chrome android (but sadly not on safari due to some restriction on that browser).
